AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: '${app-context-id}-rds'
    AllowedValues: ['${app-context-id}-rds']

Resources:
  RdsMemoryAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName:
        Fn::Sub: '${Prefix}-free-memory-alarm'
      AlarmDescription: '${app-context-id} RDS database low memory alarm'
      MetricName: 'FreeableMemory'
      Namespace: 'AWS/RDS'
      Statistic: 'Average'
      Period: 300
      EvaluationPeriods: 4
      Threshold: 209715200.0
      ComparisonOperator: 'LessThanThreshold'
      TreatMissingData: 'breaching'
      Unit: 'Bytes'
      Dimensions:
        - Name: 'DBInstanceIdentifier'
          Value: '${app-context-id}'
      AlarmActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
      OKActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
  RdsConnectionsAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName:
        Fn::Sub: '${Prefix}-db-connections-alarm'
      AlarmDescription: '${app-context-id} RDS database low number of active connections alarm'
      MetricName: 'DatabaseConnections'
      Namespace: 'AWS/RDS'
      Statistic: 'Minimum'
      Period: 60
      EvaluationPeriods: 5
      Threshold: 5.0
      ComparisonOperator: 'LessThanThreshold'
      TreatMissingData: 'breaching'
      Dimensions:
        - Name: 'DBInstanceIdentifier'
          Value: '${app-context-id}'
      AlarmActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
      OKActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
  RdsCPUSurplusCreditBalanceAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName:
        Fn::Sub: '${Prefix}-cpu-surplus-credit-balance-alarm'
      AlarmDescription: '${app-context-id} RDS database surplus credits in use alarm'
      MetricName: 'CPUSurplusCreditBalance'
      Namespace: 'AWS/RDS'
      Statistic: 'Average'
      Period: 300
      EvaluationPeriods: 60
      Threshold: 0.0
      ComparisonOperator: 'GreaterThanThreshold'
      TreatMissingData: 'breaching'
      Dimensions:
        - Name: 'DBInstanceIdentifier'
          Value: '${app-context-id}'
      AlarmActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
      OKActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
  RdsCPUSurplusCreditChargedBalanceAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName:
        Fn::Sub: '${Prefix}-cpu-surplus-credit-charged-balance-alarm'
      AlarmDescription: '${app-context-id} RDS database surplus credits charged alarm'
      MetricName: 'CPUSurplusCreditsCharged'
      Namespace: 'AWS/RDS'
      Statistic: 'Minimum'
      Period: 300
      EvaluationPeriods: 12
      Threshold: 0.0
      ComparisonOperator: 'GreaterThanThreshold'
      TreatMissingData: 'breaching'
      Dimensions:
        - Name: 'DBInstanceIdentifier'
          Value: '${app-context-id}'
      AlarmActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
      OKActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
  RdsCPUUsageAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName:
        Fn::Sub: '${Prefix}-cpu-usage-alarm'
      AlarmDescription: '${app-context-id} RDS database high CPU usage alarm'
      MetricName: 'CPUUtilization'
      Namespace: 'AWS/RDS'
      Statistic: 'Average'
      Period: 300
      EvaluationPeriods: 4
      Threshold: 80.0
      ComparisonOperator: 'GreaterThanThreshold'
      TreatMissingData: 'breaching'
      Dimensions:
        - Name: 'DBInstanceIdentifier'
          Value: '${app-context-id}'
      AlarmActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
      OKActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
  RdsDiskQueueAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName:
        Fn::Sub: '${Prefix}-disk-queue-alarm'
      AlarmDescription: '${app-context-id} RDS database disk requests queued alarm'
      MetricName: 'DiskQueueDepth'
      Namespace: 'AWS/RDS'
      Statistic: 'Average'
      Period: 300
      EvaluationPeriods: 6
      Threshold: 1.0
      ComparisonOperator: 'GreaterThanThreshold'
      TreatMissingData: 'breaching'
      Dimensions:
        - Name: 'DBInstanceIdentifier'
          Value: '${app-context-id}'
      AlarmActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
      OKActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
  RdsDiskSpaceAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName:
        Fn::Sub: '${Prefix}-disk-space-alarm'
      AlarmDescription: '${app-context-id} RDS database small amount of available space alarm'
      MetricName: 'FreeStorageSpace'
      Namespace: 'AWS/RDS'
      Statistic: 'Average'
      Period: 300
      EvaluationPeriods: 12
      Threshold: 5368709120.0
      ComparisonOperator: 'LessThanThreshold'
      TreatMissingData: 'breaching'
      Unit: 'Bytes'
      Dimensions:
        - Name: 'DBInstanceIdentifier'
          Value: '${app-context-id}'
      AlarmActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
      OKActions:
        - Fn::ImportValue: '${cloudwatch-alarms-topic}'
